import os

from backend.schemas.vacancy import VacancyCreate, VacancyPublic
from backend.schemas.applicant import ApplicantPublic
from backend.schemas.user import UserCreate
from backend.schemas.organization import OrganizationCreate
from backend.schemas.message import MessageCreate, MessagePublic

from .brower import connect

class SeleniumDriver:
    def __init__(self, port: int) -> None:
        FRONTEND_URL = os.environ["FRONTEND_URL"]
        self.driver = connect(port)
        self.driver.get(FRONTEND_URL)
    
    def register_organization(self, organization_data: OrganizationCreate): ...
    def register_user(self, user_data: UserCreate): ...
    def activate_account(self, code): ...
    def login(self, email: str, password: str): ...
    def post_vacancy(self, vacancy: VacancyCreate) -> VacancyPublic: ...
    def post_application(self, vacancy: VacancyPublic) -> ApplicantPublic: ...
    def get_applicants(self, vacancy: VacancyPublic) -> list[ApplicantPublic]: ...
    def get_messages(self) -> list[MessagePublic]: ...
    def send_message(self, user_id, message: MessageCreate): ...